server:
  port: 8080
  tomcat:
    max-http-form-post-size: 100MB
#  servlet:
#    context-path: /api


spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
    # 连接超时时间
    timeout: 1800000
  # 文件上传限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chenhai.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: dsfsdfsdfsdfsd
    user-ttl: 72000000
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
  sms:
    signName: ${sky.sms.signName}
    templateCode: ${sky.sms.templateCode}
    accessKey: ${sky.sms.accessKey}
    secret: ${sky.sms.secret}
mybatis-plus:
  global-config:
    db-config:
      id-type: auto   # 雪花算法生成ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

yuapi:
  client:
    access-key: 2odxe0zcc03b6vs8nrz00tcnclbf2rsc
    secret-key: 60j64xqg36xtpk4vn6cr5goq1zlupnnv

