sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out_v
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9rtsgDJPhQCUJsFMHK
    access-key-secret: E7ppZWhifDhXUzdKRM1I2LNyfZgqVA
    bucket-name: chenhai-misty-rain-test
  redis:
    host: localhost
    port: 6379
    password:
    database: 10